fastlane_version "2.3.12"
default_platform :ios
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
platform :ios do
before_all do
  
  end
desc "Check and Generate swiftlint.result.xml report lint file"
  lane :checking_by_lint do
swiftlint(
      mode: :lint,                            # SwiftLint mode: :lint (default) or :autocorrect
      output_file: "./swiftlint.result.xml",   # The path of the output file (optional)
      reporter: "checkstyle",                       # The custom reporter to use (optional)
      config_file: ".swiftlint.yml",       # The path of the configuration file (optional)
      ignore_exit_status: true,               # Allow fastlane to continue even if SwiftLint returns a non-zero exit status (Default: false)
      quiet: true,                            # Don't print status logs like 'Linting ' & 'Done linting' (Default: false)
      strict: false                            # Fail on warnings? (Default: false)
    )
end
after_all do |lane|
    # This block is called, only if the executed lane was successful
  end
error do |lane, exception|
    #slack(
    #  message: exception.message,
    #  success: false
    #)
  end
end
